spring.application.name=messages

#Port Service 8085 in localhost 8080 in docker
server.port=8080

#Configuration DB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://hopper.proxy.rlwy.net:49006/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:atsbzgKNrpTBDazvOcHcaNNcNfLNxvhg}
spring.datasource.driver-class-name=org.postgresql.Driver

#Configuration JPA and Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#Configuration view logs in the terminal
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=trace

debug=true

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html
